/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace EvidenceRegistry {
  export type EvidenceStruct = {
    evidenceId: BigNumberish;
    ipfsHash: string;
    fileHash: string;
    uploader: AddressLike;
    timestamp: BigNumberish;
  };

  export type EvidenceStructOutput = [
    evidenceId: bigint,
    ipfsHash: string,
    fileHash: string,
    uploader: string,
    timestamp: bigint
  ] & {
    evidenceId: bigint;
    ipfsHash: string;
    fileHash: string;
    uploader: string;
    timestamp: bigint;
  };
}

export interface EvidenceRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addEvidence"
      | "evidenceCount"
      | "evidenceRecords"
      | "getAllEvidence"
      | "getEvidence"
      | "verifyEvidence"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "EvidenceAdded" | "EvidenceVerified"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addEvidence",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "evidenceCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "evidenceRecords",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllEvidence",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEvidence",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyEvidence",
    values: [BigNumberish, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "addEvidence",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "evidenceCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "evidenceRecords",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllEvidence",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEvidence",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyEvidence",
    data: BytesLike
  ): Result;
}

export namespace EvidenceAddedEvent {
  export type InputTuple = [
    evidenceId: BigNumberish,
    uploader: AddressLike,
    fileHash: string
  ];
  export type OutputTuple = [
    evidenceId: bigint,
    uploader: string,
    fileHash: string
  ];
  export interface OutputObject {
    evidenceId: bigint;
    uploader: string;
    fileHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EvidenceVerifiedEvent {
  export type InputTuple = [evidenceId: BigNumberish, isVerified: boolean];
  export type OutputTuple = [evidenceId: bigint, isVerified: boolean];
  export interface OutputObject {
    evidenceId: bigint;
    isVerified: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EvidenceRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): EvidenceRegistry;
  waitForDeployment(): Promise<this>;

  interface: EvidenceRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addEvidence: TypedContractMethod<
    [_ipfsHash: string, _fileHash: string],
    [void],
    "nonpayable"
  >;

  evidenceCount: TypedContractMethod<[], [bigint], "view">;

  evidenceRecords: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, bigint] & {
        evidenceId: bigint;
        ipfsHash: string;
        fileHash: string;
        uploader: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getAllEvidence: TypedContractMethod<
    [],
    [EvidenceRegistry.EvidenceStructOutput[]],
    "view"
  >;

  getEvidence: TypedContractMethod<
    [_evidenceId: BigNumberish],
    [EvidenceRegistry.EvidenceStructOutput],
    "view"
  >;

  verifyEvidence: TypedContractMethod<
    [_evidenceId: BigNumberish, _fileHash: string],
    [boolean],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addEvidence"
  ): TypedContractMethod<
    [_ipfsHash: string, _fileHash: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "evidenceCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "evidenceRecords"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, bigint] & {
        evidenceId: bigint;
        ipfsHash: string;
        fileHash: string;
        uploader: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAllEvidence"
  ): TypedContractMethod<[], [EvidenceRegistry.EvidenceStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getEvidence"
  ): TypedContractMethod<
    [_evidenceId: BigNumberish],
    [EvidenceRegistry.EvidenceStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "verifyEvidence"
  ): TypedContractMethod<
    [_evidenceId: BigNumberish, _fileHash: string],
    [boolean],
    "nonpayable"
  >;

  getEvent(
    key: "EvidenceAdded"
  ): TypedContractEvent<
    EvidenceAddedEvent.InputTuple,
    EvidenceAddedEvent.OutputTuple,
    EvidenceAddedEvent.OutputObject
  >;
  getEvent(
    key: "EvidenceVerified"
  ): TypedContractEvent<
    EvidenceVerifiedEvent.InputTuple,
    EvidenceVerifiedEvent.OutputTuple,
    EvidenceVerifiedEvent.OutputObject
  >;

  filters: {
    "EvidenceAdded(uint256,address,string)": TypedContractEvent<
      EvidenceAddedEvent.InputTuple,
      EvidenceAddedEvent.OutputTuple,
      EvidenceAddedEvent.OutputObject
    >;
    EvidenceAdded: TypedContractEvent<
      EvidenceAddedEvent.InputTuple,
      EvidenceAddedEvent.OutputTuple,
      EvidenceAddedEvent.OutputObject
    >;

    "EvidenceVerified(uint256,bool)": TypedContractEvent<
      EvidenceVerifiedEvent.InputTuple,
      EvidenceVerifiedEvent.OutputTuple,
      EvidenceVerifiedEvent.OutputObject
    >;
    EvidenceVerified: TypedContractEvent<
      EvidenceVerifiedEvent.InputTuple,
      EvidenceVerifiedEvent.OutputTuple,
      EvidenceVerifiedEvent.OutputObject
    >;
  };
}
