/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace EvidenceRegistry {
  export type EvidenceStruct = {
    evidenceId: BigNumberish;
    ipfsHash: string;
    fileHash: string;
    uploader: AddressLike;
    timestamp: BigNumberish;
  };

  export type EvidenceStructOutput = [
    evidenceId: bigint,
    ipfsHash: string,
    fileHash: string,
    uploader: string,
    timestamp: bigint
  ] & {
    evidenceId: bigint;
    ipfsHash: string;
    fileHash: string;
    uploader: string;
    timestamp: bigint;
  };
}

export interface EvidenceRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addEvidence"
      | "checkIsInvestigator"
      | "getAllEvidence"
      | "grantInvestigator"
      | "investigators"
      | "revokeInvestigator"
      | "superAdmin"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "EvidenceAdded" | "RoleGranted" | "RoleRevoked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addEvidence",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "checkIsInvestigator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllEvidence",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "grantInvestigator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "investigators",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeInvestigator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "superAdmin",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "addEvidence",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkIsInvestigator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllEvidence",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantInvestigator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "investigators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeInvestigator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "superAdmin", data: BytesLike): Result;
}

export namespace EvidenceAddedEvent {
  export type InputTuple = [
    evidenceId: BigNumberish,
    ipfsHash: string,
    fileHash: string,
    uploader: AddressLike
  ];
  export type OutputTuple = [
    evidenceId: bigint,
    ipfsHash: string,
    fileHash: string,
    uploader: string
  ];
  export interface OutputObject {
    evidenceId: bigint;
    ipfsHash: string;
    fileHash: string;
    uploader: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [role: string, account: AddressLike];
  export type OutputTuple = [role: string, account: string];
  export interface OutputObject {
    role: string;
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [role: string, account: AddressLike];
  export type OutputTuple = [role: string, account: string];
  export interface OutputObject {
    role: string;
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EvidenceRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): EvidenceRegistry;
  waitForDeployment(): Promise<this>;

  interface: EvidenceRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addEvidence: TypedContractMethod<
    [_ipfsHash: string, _fileHash: string],
    [void],
    "nonpayable"
  >;

  checkIsInvestigator: TypedContractMethod<
    [_account: AddressLike],
    [boolean],
    "view"
  >;

  getAllEvidence: TypedContractMethod<
    [],
    [EvidenceRegistry.EvidenceStructOutput[]],
    "view"
  >;

  grantInvestigator: TypedContractMethod<
    [_account: AddressLike],
    [void],
    "nonpayable"
  >;

  investigators: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  revokeInvestigator: TypedContractMethod<
    [_account: AddressLike],
    [void],
    "nonpayable"
  >;

  superAdmin: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addEvidence"
  ): TypedContractMethod<
    [_ipfsHash: string, _fileHash: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "checkIsInvestigator"
  ): TypedContractMethod<[_account: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "getAllEvidence"
  ): TypedContractMethod<[], [EvidenceRegistry.EvidenceStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "grantInvestigator"
  ): TypedContractMethod<[_account: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "investigators"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "revokeInvestigator"
  ): TypedContractMethod<[_account: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "superAdmin"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "EvidenceAdded"
  ): TypedContractEvent<
    EvidenceAddedEvent.InputTuple,
    EvidenceAddedEvent.OutputTuple,
    EvidenceAddedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;

  filters: {
    "EvidenceAdded(uint256,string,string,address)": TypedContractEvent<
      EvidenceAddedEvent.InputTuple,
      EvidenceAddedEvent.OutputTuple,
      EvidenceAddedEvent.OutputObject
    >;
    EvidenceAdded: TypedContractEvent<
      EvidenceAddedEvent.InputTuple,
      EvidenceAddedEvent.OutputTuple,
      EvidenceAddedEvent.OutputObject
    >;

    "RoleGranted(string,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(string,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
  };
}
